$lines = @(
'# Video / Audio Subtitler',
'',
'Local Python tool for generating transcripts, WebVTT subtitles, MP3 audio exports, and subtitled MP4 videos from audio or video files.',
'',
'The app can process a single media file or recursively process every supported audio/video file inside a folder and its subfolders.',
'',
'---',
'',
'## Features',
'',
'- Accepts a single audio/video file or a folder path.',
'- Recursively scans folders and subfolders for supported media files.',
'- Generates a plain text transcript.',
'- Generates a WebVTT subtitle file.',
'- Generates an MP3 audio export.',
'- Creates a burned-in subtitle video.',
'- Creates an optional/selectable subtitle video.',
'- Skips files that already have all expected output files.',
'- For audio-only files, creates a video using a matching image if available.',
'- If no matching image is found, creates a blank gray 16:9 background.',
'- Uses FFmpeg for media conversion and subtitle rendering.',
'- Uses Whisper transcription through the project transcription wrapper.',
'',
'---',
'',
'## Supported Input Formats',
'',
'### Audio',
'',
'- `.mp3`',
'- `.wav`',
'- `.m4a`',
'- `.aac`',
'- `.flac`',
'- `.ogg`',
'- `.wma`',
'',
'### Video',
'',
'- `.mp4`',
'- `.mov`',
'- `.mkv`',
'- `.avi`',
'- `.webm`',
'- `.m4v`',
'',
'### Background Images for Audio Files',
'',
'For audio-only input files, the app looks for a matching image in the same folder.',
'',
'Example audio file:',
'',
'```text',
'01-example.mp3',
'```',
'',
'Matching image names checked:',
'',
'```text',
'01-example.jpg',
'01-example.jpeg',
'01-example.png',
'```',
'',
'If no matching image exists, the app creates a blank gray 1920x1080 background automatically.',
'',
'---',
'',
'## Output Files',
'',
'For an input file named:',
'',
'```text',
'nn-filename.mp4',
'```',
'',
'or:',
'',
'```text',
'nn-filename.mp3',
'```',
'',
'the app creates these files in the same folder as the source file:',
'',
'```text',
'nn-filename-burned-subtitles.mp4',
'nn-filename-optional-subtitles.mp4',
'nn-filename-transcript.txt',
'nn-filename-audio.mp3',
'nn-filename-subtitles.vtt',
'```',
'',
'### Output File Details',
'',
'| File | Purpose |',
'|---|---|',
'| `nn-filename-burned-subtitles.mp4` | MP4 video with subtitles permanently burned into the image |',
'| `nn-filename-optional-subtitles.mp4` | MP4 video with subtitles embedded as a selectable subtitle track |',
'| `nn-filename-transcript.txt` | Plain text transcript |',
'| `nn-filename-audio.mp3` | MP3 audio export |',
'| `nn-filename-subtitles.vtt` | WebVTT subtitle file |',
'',
'---',
'',
'## Skip Behavior',
'',
'The app checks whether all expected output files already exist.',
'',
'If all five output files are found, the source file is skipped:',
'',
'```text',
'nn-filename-burned-subtitles.mp4',
'nn-filename-optional-subtitles.mp4',
'nn-filename-transcript.txt',
'nn-filename-audio.mp3',
'nn-filename-subtitles.vtt',
'```',
'',
'This makes it safe to re-run the app on the same folder after adding more files.',
'',
'---',
'',
'## Requirements',
'',
'### Python',
'',
'This project uses Python with a virtual environment.',
'',
'Check Python:',
'',
'```powershell',
'python --version',
'```',
'',
'### FFmpeg',
'',
'FFmpeg and FFprobe must be installed and available on the system PATH.',
'',
'Check FFmpeg:',
'',
'```powershell',
'ffmpeg -version',
'```',
'',
'Check FFprobe:',
'',
'```powershell',
'ffprobe -version',
'```',
'',
'### Python Packages',
'',
'Install project dependencies inside the virtual environment:',
'',
'```powershell',
'python -m pip install -r requirements.txt',
'```',
'',
'---',
'',
'## Setup',
'',
'From the project root:',
'',
'```powershell',
'python -m venv .venv',
'.\.venv\Scripts\Activate.ps1',
'python -m pip install -r requirements.txt',
'```',
'',
'If PowerShell blocks script activation, run:',
'',
'```powershell',
'Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass',
'.\.venv\Scripts\Activate.ps1',
'```',
'',
'---',
'',
'## Running the App',
'',
'From the project root, with the virtual environment activated:',
'',
'```powershell',
'python main.py',
'```',
'',
'The app will ask for:',
'',
'1. A single audio/video file path, or',
'2. A folder path containing audio/video files.',
'',
'Then it will ask which Whisper model to use.',
'',
'The app automatically creates both subtitle video versions, so it does not ask whether to burn or embed subtitles.',
'',
'---',
'',
'## Example: Process One File',
'',
'Input:',
'',
'```text',
'C:\Media\01-introduction.mp4',
'```',
'',
'Outputs:',
'',
'```text',
'C:\Media\01-introduction-burned-subtitles.mp4',
'C:\Media\01-introduction-optional-subtitles.mp4',
'C:\Media\01-introduction-transcript.txt',
'C:\Media\01-introduction-audio.mp3',
'C:\Media\01-introduction-subtitles.vtt',
'```',
'',
'---',
'',
'## Example: Process a Folder Recursively',
'',
'Input:',
'',
'```text',
'C:\Media\Course',
'```',
'',
'The app will scan that folder and its subfolders for supported audio/video files.',
'',
'---',
'',
'## Whisper Model Choices',
'',
'When the app starts, it asks which Whisper model to use:',
'',
'| Option | Model | Notes |',
'|---|---|---|',
'| 1 | `tiny` | Fastest, lowest accuracy |',
'| 2 | `base` | Good default for testing |',
'| 3 | `small` | Better quality |',
'| 4 | `medium` | Slower, better quality |',
'| 5 | `large-v3` | Slowest, best quality |',
'',
'Default:',
'',
'```text',
'base',
'```',
'',
'---',
'',
'## Audio File Background Images',
'',
'For audio files, the app needs a visual background so it can create subtitled MP4 videos.',
'',
'If the audio file is:',
'',
'```text',
'07-topic.mp3',
'```',
'',
'the app checks for:',
'',
'```text',
'07-topic.jpg',
'07-topic.jpeg',
'07-topic.png',
'```',
'',
'If one exists, it is used as the video background.',
'',
'If none exists, a blank gray 1920x1080 image is generated automatically.',
'',
'---',
'',
'## Temporary Files',
'',
'The app may create a `temp` folder beside processed media files for intermediate working files, such as:',
'',
'- normalized WAV audio for transcription',
'- base video files for audio-only inputs',
'- generated gray background images',
'',
'These files are working files and can usually be deleted after processing if the final outputs were created successfully.',
'',
'---',
'',
'## Project Structure',
'',
'```text',
'Video - Audio Subtitler',
'|-- Documentation',
'|   |-- readme maker.ps1',
'|   |-- Video-Audio-Subtitler-Documentation.md',
'|-- libraries',
'|   |-- __init__.py',
'|   |-- Sx9FFmpeg.py',
'|   |-- Sx9MediaInspector.py',
'|   |-- Sx9PathUtils.py',
'|   |-- Sx9SubtitleRenderer.py',
'|   |-- Sx9VTTGenerator.py',
'|   |-- Sx9Whisper.py',
'|-- models',
'|   |-- __init__.py',
'|   |-- Sx9SubtitlingJob.py',
'|   |-- Sx9TranscriptionSegment.py',
'|-- ffmpeger.ps1',
'|-- main.py',
'|-- README.md',
'|-- requirements.txt',
'```',
'',
'---',
'',
'## Main Components',
'',
'### `main.py`',
'',
'Command-line entry point and workflow coordinator.',
'',
'Responsibilities:',
'',
'- asks for file/folder input',
'- finds supported media files',
'- manages batch processing',
'- skips completed files',
'- coordinates audio extraction, transcription, subtitle generation, and video rendering',
'',
'### `libraries/Sx9FFmpeg.py`',
'',
'Wrapper around FFmpeg and FFprobe.',
'',
'Used for:',
'',
'- checking FFmpeg availability',
'- extracting audio from video',
'- normalizing audio',
'- creating video from image and audio',
'- burning subtitles',
'- embedding subtitles',
'',
'### `libraries/Sx9MediaInspector.py`',
'',
'Detects supported media types and validates images.',
'',
'### `libraries/Sx9SubtitleRenderer.py`',
'',
'Applies subtitles by choosing burned or embedded subtitle rendering.',
'',
'### `libraries/Sx9VTTGenerator.py`',
'',
'Creates WebVTT subtitle files from transcription segments.',
'',
'### `libraries/Sx9Whisper.py`',
'',
'Handles transcription and transcript writing.',
'',
'---',
'',
'## Troubleshooting',
'',
'### FFmpeg not found',
'',
'If FFmpeg or FFprobe is unavailable, confirm they work in PowerShell:',
'',
'```powershell',
'ffmpeg -version',
'ffprobe -version',
'```',
'',
'If they do not work, install FFmpeg and add its `bin` folder to your PATH.',
'',
'### No media files found',
'',
'Confirm the folder contains files with supported extensions:',
'',
'```text',
'.mp3 .wav .m4a .aac .flac .ogg .wma',
'.mp4 .mov .mkv .avi .webm .m4v',
'```',
'',
'### File skipped unexpectedly',
'',
'The app skips a source file only when all five expected output files already exist.',
'',
'Delete one or more output files if you want the app to regenerate that source file.',
'',
'### Audio file has no background image',
'',
'This is allowed.',
'',
'The app will create a blank gray background automatically.',
'',
'---',
'',
'## Recommended `.gitignore`',
'',
'Generated media and local environment files should usually not be committed.',
'',
'Recommended ignores:',
'',
'```text',
'.venv/',
'__pycache__/',
'*.pyc',
'output/',
'temp/',
'.idea/',
'.DS_Store',
'Thumbs.db',
'```',
'',
'---',
'',
'## Status',
'',
'Current workflow:',
'',
'1. Select a file or folder.',
'2. Recursively discover supported media.',
'3. Skip completed files.',
'4. Extract or normalize audio.',
'5. Transcribe audio.',
'6. Write transcript.',
'7. Write VTT subtitles.',
'8. Export MP3 audio.',
'9. Create burned subtitle video.',
'10. Create optional subtitle video.'
)

$readmePath = Join-Path $PSScriptRoot '..\README.md'
$lines | Set-Content -Path $readmePath -Encoding UTF8

Write-Host "README.md has been updated:"
Write-Host (Resolve-Path $readmePath)